-- =============================================================================
-- @file        database/schema.sql
-- @layer       6 - Datenbank
-- @description Der Bauplan der Datenbank. Schicht 6 von 6.
--              Vorherige Schicht: src/Repositories/ (z. B. MitgliedRepository.php)
--
--              Diese Datei ist die einzige Wahrheit darüber, wie die Datenbank
--              aussieht. Wer eine Tabelle ändert, ändert sie HIER und sagt es
--              im Team - sonst hat jede Person eine andere Datenbank.
--
--              Datenbank: PostgreSQL bei Supabase, siehe
--              docs/decisions/ADR-0017-postgresql-auf-supabase.md
--
-- SO WIRD SIE EINGESPIELT
--              1. Supabase-Dashboard öffnen, Projekt auswählen
--              2. Links "SQL Editor", "New query"
--              3. Den ganzen Inhalt dieser Datei einfügen, "Run"
--
--              Zuerst immer in schwitzkasten-dev, erst danach in Produktion.
--
-- STAND        Feature Mitglieder-Login (Mitte): die acht users-Tabellen der
--              Login-Bibliothek delight-im/auth und unsere Tabelle mitglieder.
--              Feature Programm-Details: programme, merkmale und coaches.
--              Feature Mitgliedschaften: tarife und mitgliedschaften.
--              Feature Nachweise: nachweise (Ausweisprüfung, ohne Bilder).
--              Feature Terminkalender: kurstermine, kursbuchungen,
--              verfuegbarkeiten und probetrainings.
--              Hosting auf Vercel: sitzungen (PHP-Sitzungen in der Datenbank).
--              Feature Bewertungen: bewertungen.
--              Feature Profilbilder: profilbilder.
--              Die auskommentierte Tabelle in der Mitte zeigt die Konventionen.
--
--              Die Datei darf mehrfach eingespielt werden: CREATE ... IF NOT
--              EXISTS lässt vorhandene Tabellen und ihre Daten in Ruhe. Eine
--              GEÄNDERTE Spalte in einer vorhandenen Tabelle kommt so aber
--              nicht an - dafür braucht es ein ALTER TABLE.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Zeitzone
-- -----------------------------------------------------------------------------
-- Die App rechnet in Berliner Zeit (src/bootstrap.php). Die Datenbank muss
-- dasselbe tun, sonst liefern CURRENT_DATE und LOCALTIMESTAMP kurz nach
-- Mitternacht noch den Vortag - Supabase steht ab Werk auf UTC.
--
-- Gilt für jede NEUE Verbindung, also ab dem nächsten Seitenaufruf.
ALTER ROLE postgres SET timezone TO 'Europe/Berlin';


-- -----------------------------------------------------------------------------
-- KONVENTIONEN FÜR NEUE TABELLEN
-- -----------------------------------------------------------------------------
-- Tabellennamen    kleingeschrieben, Mehrzahl, deutsch:  kurse, produkte, buchungen
-- Spaltennamen     kleingeschrieben, mit Unterstrich:    erstellt_am, kurs_id
-- Keine Umlaute    in Tabellen- und Spaltennamen (aber gerne in den Daten)
-- Immer dabei      id als Primärschlüssel, erstellt_am als Zeitstempel
-- Fremdschlüssel   heißen <tabelle_einzahl>_id, z. B. kurs_id
-- Indexnamen       idx_<tabelle>_<spalten> - in PostgreSQL gilt ein Indexname
--                  für die ganze Datenbank, nicht nur für eine Tabelle
-- Fremdschlüssel   brauchen einen eigenen Index. PostgreSQL legt ihn anders
--                  als MySQL NICHT von selbst an.
-- Zugriffsschutz   jede Tabelle bekommt am Ende der Datei ENABLE ROW LEVEL
--                  SECURITY, siehe dort
--
-- Die folgende Tabelle ist ein VOLLSTÄNDIGES BEISPIEL und absichtlich
-- auskommentiert. Zum Anlegen eines echten Features: kopieren, umbenennen,
-- Kommentarzeichen entfernen.
-- -----------------------------------------------------------------------------

-- CREATE TABLE IF NOT EXISTS beispiel_eintraege (
--     -- Zählt von selbst hoch, muss beim Einfügen nie mitgeschickt werden.
--     id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--
--     -- varchar mit Längenangabe statt text, solange die Länge absehbar ist.
--     name         varchar(120) NOT NULL,
--     tag          varchar(20)  NOT NULL,
--
--     -- (0) = ohne Sekundenbruchteile. PHP bekommt dann "18:00:00" und
--     -- nicht "18:00:00.123456".
--     uhrzeit      time(0)      NOT NULL,
--
--     -- NULL erlaubt heißt: "diese Angabe ist freiwillig".
--     beschreibung text         NULL,
--
--     -- Wird beim Einfügen automatisch gesetzt. LOCALTIMESTAMP ist die
--     -- Uhrzeit in Berlin (siehe Zeitzone oben), ohne Zeitzonen-Anhang.
--     erstellt_am  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0)
-- );
--
-- -- Ein Index beschleunigt genau die Abfragen, nach denen oft gesucht wird.
-- CREATE INDEX IF NOT EXISTS idx_beispiel_eintraege_tag ON beispiel_eintraege (tag);
--
-- ALTER TABLE beispiel_eintraege ENABLE ROW LEVEL SECURITY;


-- -----------------------------------------------------------------------------
-- FEATURE MITGLIEDER-LOGIN - Tabellen der Login-Bibliothek
-- -----------------------------------------------------------------------------
-- Übernommen aus vendor/delight-im/auth/Database/PostgreSQL.sql (Version 9),
-- ergänzt nur um IF NOT EXISTS, damit die Datei wiederholbar bleibt.
-- Die Bibliothek erwartet genau diese Namen und Spalten. Deshalb weichen sie
-- von unseren Konventionen ab (englisch, keine erstellt_am-Spalte).
-- NICHT umbenennen und keine Spalten ändern, sonst bricht der Login.
--
-- Wofür die Tabellen da sind:
--   users                Konto: E-Mail, Passwort-Hash, Status
--   users_resets         offene "Passwort vergessen"-Anfragen (Token-Hash)
--   users_throttling     Zähler gegen zu viele Fehlversuche
--   users_audit_log      Protokoll: Registrierung, Login, Logout ...
--   users_confirmations  E-Mail-Bestätigung      (von uns noch nicht genutzt)
--   users_remembered     "Angemeldet bleiben"     (von uns noch nicht genutzt)
--   users_2fa, users_otps  Zwei-Faktor-Anmeldung (von uns noch nicht genutzt)
-- Die ungenutzten Tabellen fragt die Bibliothek trotzdem ab - sie müssen da sein.
-- Siehe docs/decisions/ADR-0005-login-bibliothek.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "users" (
	"id" SERIAL PRIMARY KEY,
	"email" VARCHAR(249) UNIQUE NOT NULL,
	"password" VARCHAR(255) NOT NULL COLLATE "C",
	"username" VARCHAR(100) DEFAULT NULL,
	"status" SMALLINT NOT NULL DEFAULT 0 CHECK ("status" >= 0),
	"verified" SMALLINT NOT NULL DEFAULT 0 CHECK ("verified" >= 0 AND "verified" <= 1),
	"resettable" SMALLINT NOT NULL DEFAULT 1 CHECK ("resettable" >= 0 AND "resettable" <= 1),
	"roles_mask" INTEGER NOT NULL DEFAULT 0 CHECK ("roles_mask" >= 0),
	"registered" INTEGER NOT NULL CHECK ("registered" >= 0),
	"last_login" INTEGER DEFAULT NULL CHECK ("last_login" >= 0),
	"force_logout" INTEGER NOT NULL DEFAULT 0 CHECK ("force_logout" >= 0)
);

CREATE TABLE IF NOT EXISTS "users_2fa" (
	"id" BIGSERIAL PRIMARY KEY,
	"user_id" INTEGER NOT NULL CHECK ("user_id" >= 0),
	"mechanism" SMALLINT NOT NULL CHECK ("mechanism" >= 0),
	"seed" VARCHAR(255) DEFAULT NULL COLLATE "C",
	"created_at" INTEGER NOT NULL CHECK ("created_at" >= 0),
	"expires_at" INTEGER DEFAULT NULL CHECK ("expires_at" >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_2fa_user_id_mechanism_uq" ON "users_2fa" ("user_id", "mechanism");

CREATE TABLE IF NOT EXISTS "users_audit_log" (
	"id" BIGSERIAL PRIMARY KEY,
	"user_id" INTEGER DEFAULT NULL CHECK ("user_id" >= 0),
	"event_at" INTEGER NOT NULL CHECK ("event_at" >= 0),
	"event_type" VARCHAR(128) NOT NULL COLLATE "C",
	"admin_id" INTEGER DEFAULT NULL CHECK ("admin_id" >= 0),
	"ip_address" INET DEFAULT NULL,
	"user_agent" TEXT DEFAULT NULL,
	"details_json" JSONB DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS "users_audit_log_event_at_ix" ON "users_audit_log" ("event_at");
CREATE INDEX IF NOT EXISTS "users_audit_log_user_id_event_at_ix" ON "users_audit_log" ("user_id", "event_at");
CREATE INDEX IF NOT EXISTS "users_audit_log_user_id_event_type_event_at_ix" ON "users_audit_log" ("user_id", "event_type", "event_at");

CREATE TABLE IF NOT EXISTS "users_confirmations" (
	"id" SERIAL PRIMARY KEY,
	"user_id" INTEGER NOT NULL CHECK ("user_id" >= 0),
	"email" VARCHAR(249) NOT NULL,
	"selector" VARCHAR(16) UNIQUE NOT NULL COLLATE "C",
	"token" VARCHAR(255) NOT NULL COLLATE "C",
	"expires" INTEGER NOT NULL CHECK ("expires" >= 0)
);
CREATE INDEX IF NOT EXISTS "users_confirmations_email_expires_ix" ON "users_confirmations" ("email", "expires");
CREATE INDEX IF NOT EXISTS "users_confirmations_user_id_ix" ON "users_confirmations" ("user_id");

CREATE TABLE IF NOT EXISTS "users_otps" (
	"id" BIGSERIAL PRIMARY KEY,
	"user_id" INTEGER NOT NULL CHECK ("user_id" >= 0),
	"mechanism" SMALLINT NOT NULL CHECK ("mechanism" >= 0),
	"single_factor" SMALLINT NOT NULL DEFAULT 0 CHECK ("single_factor" >= 0 AND "single_factor" <= 1),
	"selector" VARCHAR(24) NOT NULL COLLATE "C",
	"token" VARCHAR(255) NOT NULL COLLATE "C",
	"expires_at" INTEGER DEFAULT NULL CHECK ("expires_at" >= 0)
);
CREATE INDEX IF NOT EXISTS "users_otps_user_id_mechanism_ix" ON "users_otps" ("user_id", "mechanism");
CREATE INDEX IF NOT EXISTS "users_otps_selector_user_id_ix" ON "users_otps" ("selector", "user_id");

CREATE TABLE IF NOT EXISTS "users_remembered" (
	"id" BIGSERIAL PRIMARY KEY,
	"user" INTEGER NOT NULL CHECK ("user" >= 0),
	"selector" VARCHAR(24) UNIQUE NOT NULL COLLATE "C",
	"token" VARCHAR(255) NOT NULL COLLATE "C",
	"expires" INTEGER NOT NULL CHECK ("expires" >= 0)
);
CREATE INDEX IF NOT EXISTS "users_remembered_user_ix" ON "users_remembered" ("user");

CREATE TABLE IF NOT EXISTS "users_resets" (
	"id" BIGSERIAL PRIMARY KEY,
	"user" INTEGER NOT NULL CHECK ("user" >= 0),
	"selector" VARCHAR(20) UNIQUE NOT NULL COLLATE "C",
	"token" VARCHAR(255) NOT NULL COLLATE "C",
	"expires" INTEGER NOT NULL CHECK ("expires" >= 0)
);
CREATE INDEX IF NOT EXISTS "users_resets_user_expires_ix" ON "users_resets" ("user", "expires");

CREATE TABLE IF NOT EXISTS "users_throttling" (
	"bucket" VARCHAR(44) PRIMARY KEY COLLATE "C",
	"tokens" REAL NOT NULL CHECK ("tokens" >= 0),
	"replenished_at" INTEGER NOT NULL CHECK ("replenished_at" >= 0),
	"expires_at" INTEGER NOT NULL CHECK ("expires_at" >= 0)
);
CREATE INDEX IF NOT EXISTS "users_throttling_expires_at_ix" ON "users_throttling" ("expires_at");


-- -----------------------------------------------------------------------------
-- FEATURE MITGLIEDER-LOGIN - unsere eigenen Stammdaten
-- -----------------------------------------------------------------------------
-- Die Bibliothek kennt nur E-Mail und Passwort. Alles Fachliche über ein
-- Mitglied steht hier, verbunden über user_id. Spätere Features (Verträge,
-- Buchungen, Zahlungen) verweisen auf mitglieder.id, nicht auf users.
CREATE TABLE IF NOT EXISTS mitglieder (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Genau ein Mitglied pro Konto, deshalb UNIQUE.
    user_id     integer      NOT NULL,

    vorname     varchar(100) NOT NULL,
    nachname    varchar(100) NOT NULL,
    erstellt_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT uniq_user_id UNIQUE (user_id),

    -- Wird ein Konto gelöscht, verschwinden seine Stammdaten mit.
    CONSTRAINT fk_mitglieder_users
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- FEATURE PROGRAMM-DETAILS - Merkmale und Coaches der drei Programmseiten
-- -----------------------------------------------------------------------------
-- Was vorher fest in programme/strength.php, move.php und fight.php stand,
-- kommt jetzt aus der Datenbank. Die Seiten selbst bleiben getrennte Dateien,
-- nur ihr unterer Teil wird nachgeladen.
--
-- Drei Tabellen statt einer, weil ein Programm MEHRERE Merkmale und MEHRERE
-- Coaches hat. Alles in eine Tabelle zu quetschen hiesse, Spalten wie
-- level_1, level_2, level_3 anzulegen - und dann ist bei drei Schluss.
--
-- Siehe docs/decisions/ADR-0007-programm-details-aus-der-datenbank.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS programme (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Verbindet die Zeile mit der Seite: programme/move.php fragt 'move' ab.
    -- Steht in der URL und im Dateinamen, deshalb ohne Umlaute.
    slug        varchar(40)  NOT NULL,

    name        varchar(60)  NOT NULL,
    erstellt_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT uniq_slug UNIQUE (slug)
);


-- Die aufklappbaren Bloecke unter dem Text. Eine Zeile = eine Zeile im
-- Aufklappbereich.
--
-- 'fokus' hat pro Programm genau EINEN Eintrag und ist reine Information.
-- 'level' und 'format' haben MEHRERE - daraus werden die Schaltflaechen,
-- zwischen denen Besucher waehlen. Die Seite erkennt den Unterschied an der
-- Anzahl, nicht an einem zusaetzlichen Schalter.
CREATE TABLE IF NOT EXISTS merkmale (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programm_id  integer     NOT NULL,

    -- CHECK statt freiem Text: Die Datenbank laesst dann gar keinen
    -- Tippfehler zu. Neue Art? Hier ergaenzen UND in ProgrammRepository::ARTEN.
    art          text        NOT NULL CHECK (art IN ('fokus', 'level', 'format')),

    -- Ueberschrift der Schaltflaeche, z. B. "Small Group".
    titel        varchar(80) NOT NULL,

    -- Der Text, der nach dem Aufklappen erscheint.
    beschreibung text        NOT NULL,

    -- Reihenfolge innerhalb einer Art. Kleinere Zahl steht weiter oben.
    position     smallint    NOT NULL DEFAULT 0,

    erstellt_am  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_merkmale_programme
        FOREIGN KEY (programm_id) REFERENCES programme (id)
        ON DELETE CASCADE
);

-- Genau die Abfrage, die das Repository macht: alles zu einem Programm,
-- sortiert nach Art und Position.
CREATE INDEX IF NOT EXISTS idx_merkmale_programm_art_position
    ON merkmale (programm_id, art, position);


-- Die Coaches im gelben Kasten rechts.
CREATE TABLE IF NOT EXISTS coaches (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programm_id  integer      NOT NULL,

    name         varchar(80)  NOT NULL,

    -- Die kursive Zeile unter dem Namen: welche Art Training diese Person macht.
    schwerpunkt  varchar(160) NOT NULL,

    -- NUR der Dateiname, z. B. 'lena-brandt.jpg'. Der Ordner steht im
    -- Repository, die vollstaendige URL baut erst die Seite mit BASE_URL
    -- zusammen. So muss beim Verschieben des Ordners nichts in der
    -- Datenbank geaendert werden.
    bild         varchar(160) NOT NULL,

    -- Text fuer das alt-Attribut des Bildes (Pflicht, siehe assets/img/README.md).
    bild_alt     varchar(200) NOT NULL,

    position     smallint     NOT NULL DEFAULT 0,
    erstellt_am  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_coaches_programme
        FOREIGN KEY (programm_id) REFERENCES programme (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_coaches_programm_position
    ON coaches (programm_id, position);


-- -----------------------------------------------------------------------------
-- FEATURE GEMERKTE AUSWAHL - was ein Mitglied sich auf den Programmseiten merkt
-- -----------------------------------------------------------------------------
-- Wer angemeldet ist und auf einer Programmseite "Auswahl merken" klickt,
-- bekommt hier eine Zeile. Nicht angemeldete Besucher behalten ihre Auswahl
-- weiterhin nur im localStorage des Browsers.
--
-- EINE Zeile pro Mitglied und Programm, mit zwei Spalten statt zwei Zeilen.
-- Das widerspricht nicht der Begruendung aus ADR-0007 gegen level_1, level_2:
-- Dort ging es um eine unbekannte ANZAHL von Eintraegen. Hier sind es genau
-- die Arten, die merkmale.art ohnehin festlegt - eine vierte Art braeuchte so
-- oder so eine Schema-Aenderung.
--
-- Siehe docs/decisions/ADR-0008-gemerkte-auswahl-am-konto.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mitglied_auswahl (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Zeigt auf mitglieder.id, NICHT auf users.id - dieselbe Regel wie fuer
    -- alle fachlichen Tabellen, siehe Kommentar bei mitglieder oben.
    mitglied_id  integer NOT NULL,

    programm_id  integer NOT NULL,

    -- NULL erlaubt: Ein Programm koennte irgendwann nur Level oder nur
    -- Format anbieten. Beide NULL kommt nicht vor - der Endpunkt lehnt das ab.
    level_id     integer NULL,
    format_id    integer NULL,

    erstellt_am  timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Zeitpunkt der letzten Aenderung. PostgreSQL kennt kein "ON UPDATE
    -- CURRENT_TIMESTAMP" - das Repository setzt die Spalte beim Ueberschreiben
    -- selbst, siehe MitgliedAuswahlRepository::merken().
    geaendert_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Hoechstens eine gemerkte Auswahl je Mitglied und Programm. Genau darauf
    -- stuetzt sich das INSERT ... ON CONFLICT im Repository.
    CONSTRAINT uniq_mitglied_programm UNIQUE (mitglied_id, programm_id),

    CONSTRAINT fk_auswahl_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_auswahl_programme
        FOREIGN KEY (programm_id) REFERENCES programme (id)
        ON DELETE CASCADE,

    -- SET NULL statt CASCADE: Faellt ein einzelnes Level weg, soll die
    -- gemerkte Zeile bleiben - nur eben ohne Level. Bei CASCADE waere auch
    -- das gemerkte Format mit verschwunden.
    CONSTRAINT fk_auswahl_level
        FOREIGN KEY (level_id) REFERENCES merkmale (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_auswahl_format
        FOREIGN KEY (format_id) REFERENCES merkmale (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mitglied_auswahl_programm ON mitglied_auswahl (programm_id);
CREATE INDEX IF NOT EXISTS idx_mitglied_auswahl_level    ON mitglied_auswahl (level_id);
CREATE INDEX IF NOT EXISTS idx_mitglied_auswahl_format   ON mitglied_auswahl (format_id);


-- -----------------------------------------------------------------------------
-- FEATURE MITGLIEDSCHAFTEN - der Katalog
-- -----------------------------------------------------------------------------
-- Was das Studio anbietet und was es kostet. Vier Zeilen, gepflegt in
-- database/seed.sql. Diese Tabelle beschreibt das ANGEBOT, nicht die Verträge -
-- die stehen weiter unten in mitgliedschaften.
--
-- Siehe docs/decisions/ADR-0009-mitgliedschaften-datenmodell.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tarife (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Stabiler Schlüssel für Code und Seed: 'basis', 'wellness', 'kurse',
    -- 'premium'. Die id ist auf jedem Rechner eine andere, die kennung nicht.
    kennung          varchar(20)  NOT NULL,

    name             varchar(60)  NOT NULL,
    beschreibung     varchar(255) NOT NULL,

    -- numeric statt real: 44.90 ist als Gleitkommazahl nicht exakt 44.90, und
    -- bei Geldbeträgen summieren sich solche Ungenauigkeiten auf.
    -- NULL heißt: diesen Tarif gibt es für diese Preisgruppe nicht.
    preis_standard   numeric(6,2) NOT NULL,
    preis_ermaessigt numeric(6,2) NULL,
    preis_senior     numeric(6,2) NULL,

    -- Was der Tarif erlaubt. Absichtlich drei Spalten statt einer Stufe:
    -- Ein späteres Feature fragt "zugang_kurse = 1" ab und muss nicht wissen,
    -- welche Tarifnamen es gerade gibt.
    -- 0/1 statt boolean, damit die Abfragen mit "= 1" gültig bleiben.
    zugang_geraete   smallint     NOT NULL DEFAULT 0 CHECK (zugang_geraete  IN (0, 1)),
    zugang_wellness  smallint     NOT NULL DEFAULT 0 CHECK (zugang_wellness IN (0, 1)),
    zugang_kurse     smallint     NOT NULL DEFAULT 0 CHECK (zugang_kurse    IN (0, 1)),

    -- Reihenfolge der Karten auf der Seite. Ohne das ist sie zufällig.
    sortierung       integer      NOT NULL DEFAULT 0,

    -- Ein Tarif kann nicht gelöscht werden, sobald ein Vertrag auf ihn zeigt
    -- (Fremdschlüssel unten). Aus dem Angebot nehmen geht über diese Spalte.
    -- Gebraucht spätestens für den Eröffnungspreis der ersten 100 Mitglieder.
    aktiv            smallint     NOT NULL DEFAULT 1 CHECK (aktiv IN (0, 1)),

    erstellt_am      timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT uniq_kennung UNIQUE (kennung)
);


-- -----------------------------------------------------------------------------
-- FEATURE MITGLIEDSCHAFTEN - die Verträge
-- -----------------------------------------------------------------------------
-- Eine Zeile je abgeschlossenem Tarif. Ein Wechsel beendet die alte Zeile
-- (endet_am wird gesetzt) und legt eine neue an - die Historie bleibt damit
-- erhalten.
--
-- BEIDE DATUMSSPALTEN SIND EINSCHLIESSLICH GEMEINT:
--   beginnt_am  erster Tag, an dem der Tarif gilt
--   endet_am    LETZTER Tag, an dem er gilt (nicht der erste Tag danach)
--
-- Daraus folgen die drei Zustände, die eine Zeile haben kann:
--   laufend     beginnt_am <= heute AND (endet_am IS NULL OR endet_am >= heute)
--   vorgemerkt  beginnt_am >  heute          (Wechsel zum nächsten Monatsersten)
--   vorbei      endet_am   <  heute
--
-- Eine Zeile mit beginnt_am in der ZUKUNFT ist also normal: Wechsel werden
-- zum Monatsersten vorgemerkt, nicht sofort wirksam. Wer laufende Verträge
-- sucht, darf deshalb nie nur auf endet_am IS NULL prüfen.
-- Siehe docs/decisions/ADR-0010-tarifwechsel-zum-monatsersten.md
--
-- "Nur eine laufende Mitgliedschaft pro Mitglied" lässt sich nicht als
-- Constraint ausdrücken, weil "laufend" vom heutigen Datum abhängt. Das stellt
-- MitgliedschaftRepository sicher, in einer Transaktion. Wer hier direkt per
-- SQL einfügt, umgeht das.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mitgliedschaften (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mitglied_id     integer      NOT NULL,
    tarif_id        integer      NOT NULL,

    -- Steht am Vertrag, nicht am Mitglied: Der Studentenstatus endet
    -- irgendwann, der Seniorenstatus beginnt irgendwann.
    preisgruppe     text         NOT NULL DEFAULT 'standard'
                                 CHECK (preisgruppe IN ('standard', 'ermaessigt', 'senior')),

    -- Kopie aus tarife zum Zeitpunkt des Abschlusses, absichtlich redundant:
    -- Eine spätere Preisänderung im Katalog darf laufende Verträge nicht
    -- rückwirkend verteuern.
    preis_monatlich numeric(6,2) NOT NULL,

    -- Erster Gültigkeitstag. Liegt in der Zukunft, solange ein Wechsel nur
    -- vorgemerkt ist.
    beginnt_am      date         NOT NULL,

    -- Letzter Gültigkeitstag, einschließlich. NULL = läuft unbefristet.
    endet_am        date         NULL,

    erstellt_am     timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Wird ein Mitglied gelöscht, verschwinden seine Verträge mit.
    CONSTRAINT fk_mitgliedschaften_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE,

    -- Hier ausdrücklich KEIN CASCADE: Ein Tarif, auf den Verträge zeigen,
    -- darf nicht löschbar sein. Aus dem Angebot nehmen geht über tarife.aktiv.
    CONSTRAINT fk_mitgliedschaften_tarife
        FOREIGN KEY (tarif_id) REFERENCES tarife (id)
);

-- Deckt beide Abfragen ab: "alle Verträge eines Mitglieds" und
-- "der laufende Vertrag eines Mitglieds".
CREATE INDEX IF NOT EXISTS idx_mitgliedschaften_mitglied_laufzeit
    ON mitgliedschaften (mitglied_id, endet_am);

CREATE INDEX IF NOT EXISTS idx_mitgliedschaften_tarif
    ON mitgliedschaften (tarif_id);


-- -----------------------------------------------------------------------------
-- FEATURE MITGLIEDSCHAFTEN - Nachweise für ermäßigte Preise
-- -----------------------------------------------------------------------------
-- Wer weniger zahlen will, muss es belegen: Schülerinnen und Schüler sowie
-- Studierende mit ihrem Ausweis, Seniorinnen und Senioren ab 65 mit einem
-- Lichtbildausweis.
--
-- HIER STEHT KEIN BILD UND KEIN PFAD ZU EINEM BILD. Das hochgeladene Foto
-- wird ausgelesen und sofort verworfen, es landet nie auf der Festplatte.
-- Gespeichert wird nur das Ergebnis der Prüfung. Das ist der Kern der
-- Datenschutz-Entscheidung, siehe
-- docs/decisions/ADR-0011-ausweispruefung-mit-ki.md
--
-- Ein Geburtsdatum wird ebenfalls nicht gespeichert: Wer einmal 65 ist,
-- bleibt es. Für Senioren genügt art = 'senior' mit gueltig_bis = NULL.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS nachweise (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mitglied_id integer      NOT NULL,

    -- Was belegt wurde. 'schueler' und 'student' berechtigen zum ermäßigten
    -- Preis, 'senior' zum Seniorenpreis.
    art         text         NOT NULL CHECK (art IN ('schueler', 'student', 'senior')),

    -- Letzter Tag, an dem der Nachweis gilt - einschließlich, wie bei
    -- mitgliedschaften. NULL heißt unbefristet und kommt nur bei 'senior' vor.
    gueltig_bis date         NULL,

    -- Wie geprüft wurde. 'ki' = ausgelesen von der Bilderkennung,
    -- 'demo' = im Demo-Modus von Hand eingetragen, weil kein API-Schlüssel
    -- hinterlegt ist. Der Unterschied muss sichtbar bleiben, sonst weiß
    -- später niemand mehr, welche Angaben geprüft wurden.
    quelle      text         NOT NULL CHECK (quelle IN ('ki', 'demo')),

    -- Welches Modell geprüft hat, für die Nachvollziehbarkeit. NULL im Demo-Modus.
    ki_modell   varchar(60)  NULL,

    -- Was geprüft wurde, ein Satz. Ersetzt das gelöschte Bild als Beleg, wenn
    -- jemand die Prüfung anzweifelt. Den Satz baut api/nachweise.php selbst,
    -- damit weder ein Name noch ein Geburtsdatum darin stehen kann.
    hinweis     varchar(255) NOT NULL,

    geprueft_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_nachweise_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE
);

-- Deckt die einzige häufige Abfrage ab: "hat dieses Mitglied einen
-- gültigen Nachweis dieser Art?"
CREATE INDEX IF NOT EXISTS idx_nachweise_mitglied_art
    ON nachweise (mitglied_id, art, gueltig_bis);


-- -----------------------------------------------------------------------------
-- auslastung_basis - die typische Auslastung im Wochenverlauf
--
-- Erfundene Werte. Ein echtes Studio wuerde sie aus Drehkreuzdaten gewinnen;
-- fuer die Studienarbeit stehen sie in dieser Tabelle, damit die Vorhersage
-- aus der Datenbank kommt und nicht aus dem Quelltext. Wer die Kurve aendern
-- will, aendert seed.sql - kein PHP.
--
-- Eine Zeile je Wochentag und Stunde, also 7 x 24 = 168 Zeilen.
--
-- Siehe docs/decisions/ADR-0013-auslastung-und-besuche.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS auslastung_basis (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 1 = Montag bis 7 = Sonntag, wie ISO-8601 und wie PHPs date('N').
    wochentag smallint NOT NULL,

    stunde    smallint NOT NULL,

    -- Wie viele Personen ueblicherweise zu dieser Zeit da sind.
    personen  smallint NOT NULL,

    -- Je Wochentag und Stunde genau ein Wert. Verhindert, dass ein zweiter
    -- Durchlauf von seed.sql die Kurve verdoppelt.
    CONSTRAINT uniq_wochentag_stunde UNIQUE (wochentag, stunde),

    -- Wochentag 0 oder 8 waere ein Tippfehler, den sonst niemand bemerkt.
    CONSTRAINT chk_wochentag CHECK (wochentag BETWEEN 1 AND 7),
    CONSTRAINT chk_stunde    CHECK (stunde    BETWEEN 0 AND 23)
);


-- -----------------------------------------------------------------------------
-- besuche - angekuendigte und laufende Besuche der Mitglieder
--
-- EINE Tabelle fuer beide Faelle, die der Mitgliedsbereich anbietet:
--
--   "Ich bin jetzt da"   -> beginn = jetzt,          ende = jetzt + 90 Min
--   "Ich komme um 18:00" -> beginn = heute 18:00,    ende = beginn + 90 Min
--
-- Der Unterschied liegt also nur im Startzeitpunkt, nicht in der Struktur.
-- Dadurch braucht die Auslastung genau eine Abfrage: zaehle alle Zeilen,
-- deren Zeitraum den gefragten Moment enthaelt. Begruendung und verworfene
-- Alternativen in docs/decisions/ADR-0013-auslastung-und-besuche.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS besuche (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Zeigt auf mitglieder.id, NICHT auf users.id - dieselbe Regel wie fuer
    -- alle fachlichen Tabellen, siehe Kommentar bei mitglieder oben.
    mitglied_id integer      NOT NULL,

    -- Berliner Zeit, ohne Zeitzonen-Anhang.
    beginn      timestamp(0) NOT NULL,
    ende        timestamp(0) NOT NULL,

    -- Nur fuer die Anzeige im Mitgliedsbereich ("jetzt eingecheckt" gegenueber
    -- "fuer 18:00 angekuendigt"). Fuer die Zaehlung spielt es keine Rolle.
    art         text         NOT NULL CHECK (art IN ('jetzt', 'geplant')),

    erstellt_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_besuche_mitglied
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE
);

-- Die Auslastungsabfrage sucht ueber beginn und ende. Ohne diesen
-- Index liest sie bei jedem Aufruf die ganze Tabelle.
CREATE INDEX IF NOT EXISTS idx_besuche_zeitraum ON besuche (beginn, ende);

CREATE INDEX IF NOT EXISTS idx_besuche_mitglied ON besuche (mitglied_id);


-- -----------------------------------------------------------------------------
-- FEATURE TERMINKALENDER - Kurstermine und ihre Buchungen
-- -----------------------------------------------------------------------------
-- Kurstermine sind ein WOCHENPLAN, keine Liste fester Daten: "Move, Small
-- Group, dienstags 18:00". Die konkreten Tage der nächsten zwei Wochen
-- rechnet src/Terminplan.php daraus aus. Feste Daten wären nach zwei Wochen
-- alle vorbei, und jemand müsste neue einspielen.
--
-- Gebucht wird dagegen ein KONKRETER Tag: kursbuchungen hat deshalb neben
-- dem Wochenplan-Eintrag ein Datum.
--
-- Siehe docs/decisions/ADR-0014-terminkalender-wochenplan.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS kurstermine (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programm_id    integer  NOT NULL,

    -- Das Format ist nur Einordnung ("Small Group"), keine buchbare Kategorie.
    -- Zeigt auf eine Zeile mit art = 'format' in merkmale.
    format_id      integer  NOT NULL,

    coach_id       integer  NOT NULL,

    -- 1 = Montag ... 7 = Sonntag, wie PHPs date('N').
    wochentag      smallint NOT NULL,
    beginn         time(0)  NOT NULL,
    dauer_minuten  smallint NOT NULL DEFAULT 60,

    -- 20 für Gruppenformate. Beim Einzelcoaching so viele, wie das Programm
    -- Coaches hat - das setzt seed.sql.
    max_teilnehmer smallint NOT NULL DEFAULT 20,

    -- Plätze, die JEDE Woche schon vergeben sind (Stammgäste, die nicht über
    -- die Website buchen). Belegt = Stammplätze + Buchungen. Dadurch lässt
    -- sich "ausgebucht" auch ohne zwanzig Testkonten vorführen.
    stammplaetze   smallint NOT NULL DEFAULT 0,

    erstellt_am    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_kurstermine_programme
        FOREIGN KEY (programm_id) REFERENCES programme (id) ON DELETE CASCADE,
    CONSTRAINT fk_kurstermine_merkmale
        FOREIGN KEY (format_id)   REFERENCES merkmale (id)  ON DELETE CASCADE,
    CONSTRAINT fk_kurstermine_coaches
        FOREIGN KEY (coach_id)    REFERENCES coaches (id)   ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kurstermine_programm        ON kurstermine (programm_id);
CREATE INDEX IF NOT EXISTS idx_kurstermine_format          ON kurstermine (format_id);
CREATE INDEX IF NOT EXISTS idx_kurstermine_coach_wochentag ON kurstermine (coach_id, wochentag);


CREATE TABLE IF NOT EXISTS kursbuchungen (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurstermin_id integer NOT NULL,

    -- Der konkrete Tag. Muss auf den Wochentag des Kurstermins fallen - das
    -- prüft src/Terminplan.php, bevor gespeichert wird.
    datum         date    NOT NULL,

    mitglied_id   integer NOT NULL,

    -- Wie erfahren sich das Mitglied einschätzt. Dieselben drei Stufen wie
    -- beim Probetraining.
    stufe         text    NOT NULL CHECK (stufe IN ('einsteiger', 'fortgeschritten', 'erfahren')),

    erstellt_am   timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Niemand bucht denselben Termin am selben Tag zweimal.
    CONSTRAINT uniq_termin_datum_mitglied UNIQUE (kurstermin_id, datum, mitglied_id),

    CONSTRAINT fk_kursbuchungen_kurstermine
        FOREIGN KEY (kurstermin_id) REFERENCES kurstermine (id) ON DELETE CASCADE,
    CONSTRAINT fk_kursbuchungen_mitglieder
        FOREIGN KEY (mitglied_id)   REFERENCES mitglieder (id)  ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kursbuchungen_mitglied_datum ON kursbuchungen (mitglied_id, datum);


-- -----------------------------------------------------------------------------
-- FEATURE TERMINKALENDER - Probetraining
-- -----------------------------------------------------------------------------
-- Ein Probetraining ist ein Einzeltermin mit einem Coach, unabhängig von den
-- Kursen. Wann ein Coach kann, steht als Wochenfenster in
-- verfuegbarkeiten ("montags 10 bis 13 Uhr"). src/Terminplan.php schneidet
-- daraus Termine zu je 60 Minuten und lässt die schon gebuchten weg.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS verfuegbarkeiten (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id    integer  NOT NULL,

    -- 1 = Montag ... 7 = Sonntag, wie bei kurstermine.
    wochentag   smallint NOT NULL,
    von         time(0)  NOT NULL,
    bis         time(0)  NOT NULL,

    erstellt_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT fk_verfuegbarkeiten_coaches
        FOREIGN KEY (coach_id) REFERENCES coaches (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_verfuegbarkeiten_coach_wochentag ON verfuegbarkeiten (coach_id, wochentag);


CREATE TABLE IF NOT EXISTS probetrainings (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mitglied_id integer      NOT NULL,
    coach_id    integer      NOT NULL,

    -- Beginn des 60-Minuten-Termins, Berliner Zeit.
    beginnt_am  timestamp(0) NOT NULL,

    stufe       text         NOT NULL CHECK (stufe IN ('einsteiger', 'fortgeschritten', 'erfahren')),
    erstellt_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Ein Coach, eine Uhrzeit, ein Mensch. Klicken zwei Leute gleichzeitig
    -- auf denselben Termin, weist die Datenbank den zweiten ab - das kann
    -- keine Prüfung im PHP so sicher.
    CONSTRAINT uniq_coach_beginn UNIQUE (coach_id, beginnt_am),

    CONSTRAINT fk_probetrainings_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id) ON DELETE CASCADE,
    CONSTRAINT fk_probetrainings_coaches
        FOREIGN KEY (coach_id)    REFERENCES coaches (id)    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_probetrainings_mitglied_beginn ON probetrainings (mitglied_id, beginnt_am);


-- -----------------------------------------------------------------------------
-- HOSTING AUF VERCEL - PHP-Sitzungen
-- -----------------------------------------------------------------------------
-- Auf Vercel läuft jeder Seitenaufruf in einer Funktion, die keine Festplatte
-- mit den anderen Aufrufen teilt. PHP legt Sitzungen aber normalerweise als
-- Datei ab - der nächste Aufruf fände sie nicht, und der Login wäre weg.
-- Deshalb speichert src/SitzungsSpeicher.php jede Sitzung hier.
--
-- Die Spaltennamen folgen unseren Konventionen, nicht denen von PHP. Wer hier
-- etwas ändert, ändert auch src/SitzungsSpeicher.php.
--
-- Siehe docs/decisions/ADR-0017-postgresql-auf-supabase.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sitzungen (
    -- Die Sitzungs-ID aus dem Cookie.
    id      text    PRIMARY KEY,

    -- Was PHP in $_SESSION ablegt, in PHPs eigenem Format.
    daten   text    NOT NULL,

    -- Letzter Zugriff als Unix-Zeitstempel. Danach räumt PHP abgelaufene
    -- Sitzungen weg (garbage collection).
    zuletzt integer NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sitzungen_zuletzt ON sitzungen (zuletzt);


-- -----------------------------------------------------------------------------
-- FEATURE BEWERTUNGEN
-- -----------------------------------------------------------------------------
-- Bewerten kann nur, wer ein Konto hat. Mitglied im Sinne der Karte heißt
-- aber: ein aktiver Vertrag - wer nur ein Konto hat, bewertet als
-- "kein Mitglied".
--
-- Name und Mitgliedsstatus werden beim Schreiben festgehalten, nicht bei
-- jedem Aufruf neu nachgesehen. Kündigt jemand später, bleibt sichtbar, dass
-- die Bewertung als Mitglied entstand.
--
-- Siehe docs/features/bewertungen.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bewertungen (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Wer bewertet hat. NULL nur bei den Beispielbewertungen aus seed.sql -
    -- api/bewertungen.php nimmt Bewertungen nur mit Anmeldung an.
    mitglied_id  integer       NULL,

    -- So steht der Name auf der Karte, z. B. "Lea M.".
    name         varchar(120)  NOT NULL,

    -- 1 = hatte beim Schreiben einen aktiven Vertrag.
    war_mitglied smallint      NOT NULL CHECK (war_mitglied IN (0, 1)),

    sterne       smallint      NOT NULL CHECK (sterne BETWEEN 1 AND 5),
    text         varchar(1000) NOT NULL,

    -- Pfad relativ zur BASE_URL, z. B. 'assets/img/bewertungen/lea-m.jpg'.
    -- Nur die Beispielbewertungen haben hier ein Bild. Bewertungen mit
    -- Konto zeigen das freigegebene Profilbild aus der Tabelle profilbilder
    -- (BewertungRepository); ohne Bild zeigt die Startseite eine Zitat-Kachel.
    bild         varchar(255)  NULL,

    erstellt_am  timestamp(0)  NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Eine Bewertung pro Konto. Mehrere NULL - die Beispiele - lässt
    -- PostgreSQL trotzdem zu. Der Index dahinter dient zugleich dem
    -- Fremdschlüssel.
    CONSTRAINT uniq_bewertungen_mitglied_id UNIQUE (mitglied_id),

    -- Wird ein Konto gelöscht, verschwindet seine Bewertung mit.
    CONSTRAINT fk_bewertungen_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- FEATURE FREUNDE WERBEN
-- -----------------------------------------------------------------------------
-- Ein Mitglied trägt Name und E-Mail eines Freundes ein (empfehlungen).
-- Registriert sich jemand mit genau dieser E-Mail, entsteht für den Werber
-- ein Gutschein (gutscheine): drei Monate Basisplan gratis.
--
-- Die Seite verschickt keine E-Mails. Der Werber gibt den Link zur
-- Registrierung selbst weiter; zugeordnet wird allein über die E-Mail.
--
-- Der Gutschein ändert keinen Vertrag. Er hält nur einen Zeitraum fest, in
-- dem der Basisplan nichts kostet - siehe
-- docs/decisions/ADR-0021-gutschein-als-gratiszeitraum.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS empfehlungen (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Wer eingeladen hat. Bekommt später den Gutschein.
    werber_id      integer      NOT NULL,

    -- So hat der Werber den Freund genannt. Nur für die eigene Übersicht.
    freund_name    varchar(120) NOT NULL,

    -- Kleingeschrieben, wie users.email - sonst träfe der Vergleich bei der
    -- Registrierung "Max@..." nicht. 249 wie dort.
    freund_email   varchar(249) NOT NULL,

    -- Gesetzt, sobald sich der Freund registriert hat. NULL = noch offen.
    geworben_id    integer      NULL,
    registriert_am timestamp(0) NULL,

    erstellt_am    timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Eine E-Mail kann nur einmal eingeladen werden: Wer zuerst einlädt,
    -- bekommt den Gutschein. Ohne das gäbe es für eine Registrierung
    -- mehrere Gutscheine.
    CONSTRAINT uniq_empfehlungen_freund_email UNIQUE (freund_email),

    -- Wird das Konto des Werbers gelöscht, verschwinden seine Einladungen mit.
    CONSTRAINT fk_empfehlungen_werber
        FOREIGN KEY (werber_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE,

    -- Löscht der Geworbene sein Konto, bleibt die Einladung als erfüllt
    -- stehen - der Gutschein ist verdient.
    CONSTRAINT fk_empfehlungen_geworben
        FOREIGN KEY (geworben_id) REFERENCES mitglieder (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_empfehlungen_werber ON empfehlungen (werber_id);

CREATE TABLE IF NOT EXISTS gutscheine (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Was der Werber eintippt, z. B. 'SK-7F3K9QXM'. Großbuchstaben und
    -- Ziffern ohne 0, O, 1 und I - die verwechselt man beim Abtippen.
    code          varchar(16)  NOT NULL,

    -- Wem der Gutschein gehört. Nur dieses Mitglied kann ihn einlösen:
    -- Ein erratener oder weitergegebener Code nützt niemand anderem.
    mitglied_id   integer      NOT NULL,

    -- Für welche Einladung es ihn gab. UNIQUE: höchstens ein Gutschein pro
    -- Einladung, auch wenn zwei Anfragen gleichzeitig ankommen.
    empfehlung_id integer      NOT NULL,

    -- Alle drei NULL = noch nicht eingelöst. Beide Datumsspalten sind
    -- EINSCHLIESSLICH gemeint, wie bei mitgliedschaften.
    eingeloest_am timestamp(0) NULL,
    gratis_von    date         NULL,
    gratis_bis    date         NULL,

    erstellt_am   timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    CONSTRAINT uniq_gutscheine_code UNIQUE (code),
    CONSTRAINT uniq_gutscheine_empfehlung_id UNIQUE (empfehlung_id),

    -- Eingelöst heißt: Zeitpunkt UND Zeitraum stehen da. Nie nur ein Teil.
    CONSTRAINT chk_gutscheine_eingeloest CHECK (
        (eingeloest_am IS NULL AND gratis_von IS NULL AND gratis_bis IS NULL)
        OR (eingeloest_am IS NOT NULL AND gratis_von IS NOT NULL AND gratis_bis >= gratis_von)
    ),

    CONSTRAINT fk_gutscheine_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_gutscheine_empfehlungen
        FOREIGN KEY (empfehlung_id) REFERENCES empfehlungen (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_gutscheine_mitglied ON gutscheine (mitglied_id);

-- -----------------------------------------------------------------------------
-- FEATURE PROFILBILDER
-- -----------------------------------------------------------------------------
-- Ein Bild pro Mitglied, als JPEG direkt in der Datenbank. Auf Vercel gibt es
-- keinen dauerhaften Speicher für hochgeladene Dateien - siehe
-- docs/decisions/ADR-0019-profilbilder-in-der-datenbank.md
--
-- Eigene Tabelle statt einer Spalte in mitglieder: So lädt nicht jede Abfrage
-- der Stammdaten das Bild mit, und die Datei legt die Tabelle auch in einer
-- bestehenden Datenbank an (eine neue Spalte käme per CREATE ... IF NOT
-- EXISTS nicht an).
--
-- Siehe docs/features/profilbilder.md
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS profilbilder (
    -- Zugleich Primärschlüssel: genau ein Bild pro Mitglied.
    mitglied_id  integer      PRIMARY KEY,

    -- Im Browser quadratisch zugeschnitten und verkleinert, höchstens
    -- 300 KB - das prüft api/profilbilder.php vor dem Speichern.
    bild         bytea        NOT NULL,

    -- 1 = wird bei den eigenen Bewertungen gezeigt. Anfangs an, abschalten
    -- geht in "Mein Konto" (Entscheidung im Team, 2026-09-30).
    oeffentlich  smallint     NOT NULL DEFAULT 1 CHECK (oeffentlich IN (0, 1)),

    -- Steckt in der Bildadresse (?v=...). Ein neues Bild bekommt so eine
    -- neue Adresse, und der Browser darf das alte lange zwischenspeichern.
    geaendert_am timestamp(0) NOT NULL DEFAULT LOCALTIMESTAMP(0),

    -- Wird ein Konto gelöscht, verschwindet sein Bild mit.
    CONSTRAINT fk_profilbilder_mitglieder
        FOREIGN KEY (mitglied_id) REFERENCES mitglieder (id)
        ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- ZUGRIFFSSCHUTZ - Row Level Security
-- -----------------------------------------------------------------------------
-- Supabase stellt jede Tabelle im Schema public zusätzlich über eine
-- öffentliche REST-Schnittstelle bereit. Wer den "anon"-Schlüssel des
-- Projekts kennt, könnte darüber sonst z. B. die Passwort-Hashes aus users
-- lesen.
--
-- ENABLE ROW LEVEL SECURITY OHNE eine einzige Policy heißt: Über diese
-- Schnittstelle sieht niemand eine Zeile und niemand schreibt eine. Unsere
-- App ist davon nicht betroffen - sie verbindet sich als Eigentümer der
-- Tabellen (Rolle postgres), und für den gilt RLS nicht.
--
-- NEUE TABELLE = NEUE ZEILE HIER. Sonst ist sie offen.
-- -----------------------------------------------------------------------------

ALTER TABLE users                ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_2fa            ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_audit_log      ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_confirmations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_otps           ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_remembered     ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_resets         ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_throttling     ENABLE ROW LEVEL SECURITY;
ALTER TABLE mitglieder           ENABLE ROW LEVEL SECURITY;
ALTER TABLE programme            ENABLE ROW LEVEL SECURITY;
ALTER TABLE merkmale             ENABLE ROW LEVEL SECURITY;
ALTER TABLE coaches              ENABLE ROW LEVEL SECURITY;
ALTER TABLE mitglied_auswahl     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tarife               ENABLE ROW LEVEL SECURITY;
ALTER TABLE mitgliedschaften     ENABLE ROW LEVEL SECURITY;
ALTER TABLE nachweise            ENABLE ROW LEVEL SECURITY;
ALTER TABLE auslastung_basis     ENABLE ROW LEVEL SECURITY;
ALTER TABLE besuche              ENABLE ROW LEVEL SECURITY;
ALTER TABLE kurstermine          ENABLE ROW LEVEL SECURITY;
ALTER TABLE kursbuchungen        ENABLE ROW LEVEL SECURITY;
ALTER TABLE verfuegbarkeiten     ENABLE ROW LEVEL SECURITY;
ALTER TABLE probetrainings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE sitzungen            ENABLE ROW LEVEL SECURITY;
ALTER TABLE bewertungen          ENABLE ROW LEVEL SECURITY;
ALTER TABLE empfehlungen         ENABLE ROW LEVEL SECURITY;
ALTER TABLE gutscheine           ENABLE ROW LEVEL SECURITY;
ALTER TABLE profilbilder         ENABLE ROW LEVEL SECURITY;
